plotting_parameters = {
    "mtl_sensory": {
        "figsize": (2, 2),
        "reshape_rows": 10,
        "weight_ticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "weight_ticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(10)),
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 14,
        "label_fontsize": 20,
        "auto_order": False,
        "vmin": None,
        "vmax": None,
    },
    "mtl_semantic": {
        "figsize": (2, 2),
        "reshape_rows": 10,
        "weight_ticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "weight_ticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(10)),
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 14,
        "label_fontsize": 20,
        "auto_order": True,
        "vmin": None,
        "vmax": None,
    },
    "mtl": {
        "figsize": (3, 3),
        "reshape_rows": 100,
        "subregion_display_names": ["MTL-sensory", "MTL-semantic"],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 18,
        "label_fontsize": 20,
        "auto_order": False,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx": {
        "figsize": (3, 3),
        "reshape_rows": 100,
        "subregion_display_names": ["CTX", "CTX episodes"],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 18,
        "label_fontsize": 20,
        "auto_order": True,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx_subregion_0": {
        "figsize": (2, 2),
        "reshape_rows": 10,
        "weight_ticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "weight_ticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(10)),
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 14,
        "label_fontsize": 20,
        "auto_order": True,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx_subregion_1": {
        "figsize": (2.6, 4.6),
        "reshape_rows": 25,
        "weight_ticks": [10 * i + 5 for i in range(25)],
        "weight_ticklabels": [f"A{i+1}B{j+1}" for i in range(5) for j in range(5)],
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(25)),
        "yticklabels": [f"A{i+1}B{j+1}" for i in range(5) for j in range(5)],
        "ytick_fontsize": 11,
        "label_fontsize": 18,
        "auto_order": True,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx_mtl": {
        "figsize": (3, 3),
        "subregion_post": 0,
        "subregion_pre": None,
        "row_order_attr": None,
        "row_slice": None,
        "col_order_attr": None,
        "col_slice": None,
        "ylabel": "Post Neuron\n(CTX)",
        "xlabel": "Pre Neuron\n(MTL-sensory)",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": None,
        "xticklabels": None,
        "xtick_rotation": 90,
        "yticks": None,
        "yticklabels": None,
        "tick_fontsize": 18,
        "label_fontsize": 20,
        "draw_grid": True,
        "grid_linewidth": 0.1,
        "subplots_adjust": {"left": 0.22, "bottom": 0.22, "right": 0.98, "top": 0.98},
        "vmin": None,
        "vmax": None,
    },
    "ctx_ctx": {
        "figsize": (3, 3),
        "subregion_post": 0,
        "subregion_pre": 0,
        "row_order_attr": None,
        "row_slice": None,
        "col_order_attr": None,
        "col_slice": None,
        "ylabel": "Post Neuron\n(CTX)",
        "xlabel": "Pre Neuron\n(CTX)",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "xticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "xtick_rotation": 90,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "tick_fontsize": 18,
        "label_fontsize": 20,
        "draw_grid": True,
        "grid_linewidth": 0.1,
        "subplots_adjust": {"left": 0.22, "bottom": 0.22, "right": 0.98, "top": 0.98},
        "vmin": None,
        "vmax": None,
    },
    "mtl_semantic_ctx": {
        "figsize": (3, 3),
        "subregion_post": 0,
        "subregion_pre": 0,
        "row_order_attr": None,
        "row_slice": None,
        "col_order_attr": None,
        "col_slice": None,
        "ylabel": "Post Neuron\n(MTL-semantic)",
        "xlabel": "Pre Neuron\n(CTX)",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "xticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "xtick_rotation": 90,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "tick_fontsize": 18,
        "label_fontsize": 20,
        "draw_grid": True,
        "grid_linewidth": 0.1,
        "subplots_adjust": {"left": 0.22, "bottom": 0.22, "right": 0.98, "top": 0.98},
        "vmin": None,
        "vmax": None,
    },
}
