plotting_parameters = {
    "mtl_sensory": {
        "figsize": (2, 2),
        "reshape_rows": 10,
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(10)),
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 14,
        "label_fontsize": 20,
        "auto_order": False,
        "vmin": None,
        "vmax": None,
    },
    "mtl_semantic": {
        "figsize": (2, 2),
        "reshape_rows": 10,
        "ylabel": "Neuron",
        "xlabel": "Neuron",
        "show_xticks": False,
        "show_yticks": True,
        "yticks": list(range(10)),
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 14,
        "label_fontsize": 20,
        "auto_order": True,
        "vmin": None,
        "vmax": None,
    },
    "mtl": {
        "figsize": (3, 3),
        "reshape_rows": 100,
        "ylabel": "Neuron",
        "xlabel": "Time",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": ([0, 20], None),
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 18,
        "label_fontsize": 20,
        "auto_order": False,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx": {
        "figsize": (3, 3),
        "reshape_rows": 100,
        "ylabel": "Neuron",
        "xlabel": "Time",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": ([0, 20], None),
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "ytick_fontsize": 18,
        "label_fontsize": 20,
        "auto_order": True,
        "vmin": 0,
        "vmax": 1,
    },
    "ctx_mtl": {
        "figsize": (3, 3),
        "subregion_post": 0,
        "subregion_pre": 0,
        "row_order_attr": None,
        "row_slice": None,
        "col_order_attr": None,
        "col_slice": None,
        "ylabel": "Post Neuron\n(CTX)",
        "xlabel": "Pre Neuron\n(MTL-sensory)",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "xticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "xtick_rotation": 90,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "tick_fontsize": 18,
        "label_fontsize": 20,
        "draw_grid": True,
        "grid_linewidth": 0.1,
        "subplots_adjust": {"left": 0.22, "bottom": 0.22, "right": 0.98, "top": 0.98},
        "vmin": None,
        "vmax": None,
    },
    "ctx_ctx": {
        "figsize": (3, 3),
        "subregion_post": 0,
        "subregion_pre": 0,
        "row_order_attr": None,
        "row_slice": None,
        "col_order_attr": None,
        "col_slice": None,
        "ylabel": "Post Neuron\n(CTX)",
        "xlabel": "Pre Neuron\n(CTX)",
        "show_xticks": True,
        "show_yticks": True,
        "xticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "xticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "xtick_rotation": 90,
        "yticks": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        "yticklabels": [f"A{i+1}" for i in range(5)] + [f"B{i+1}" for i in range(5)],
        "tick_fontsize": 18,
        "label_fontsize": 20,
        "draw_grid": True,
        "grid_linewidth": 0.1,
        "subplots_adjust": {"left": 0.22, "bottom": 0.22, "right": 0.98, "top": 0.98},
        "vmin": None,
        "vmax": None,
    },
}
